name: GitHub-Profile-3D-Contrib

permissions:
  contents: write

concurrency:
  group: profile-3d-${{ github.ref }}
  cancel-in-progress: false

on:
  schedule:
    # Runs daily at 18:00 UTC (≈ 03:00 JST next day)
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib

    steps:
      # 1) Checkout full history on main (avoid shallow clones)
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      # 2) Generate 3D contribution graph assets
      - name: Generate 3D SVG
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      # 3) (Optional) Post-process with Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Post-process border
        run: |
          python ./bin/change-border.py \
            profile-3d-contrib/profile-night-rainbow.svg \
            profile-3d-contrib/profile-night-rainbow-with-border.svg

      # 4) Force current UTC date for the commit (avoid old years)
      - name: Fix commit date (force current UTC date)
        run: |
          export GIT_AUTHOR_DATE="$(date -u '+%Y-%m-%d %H:%M:%S %z')"
          export GIT_COMMITTER_DATE="$GIT_AUTHOR_DATE"

      # 5) Commit & Push safely (rebase to avoid non-fast-forward)
      - name: Commit & Push
        run: |
          git config user.name  "wahabu"
          # ⬇️ Replace with your real noreply (from GitHub Settings → Emails)
          git config user.email "52596957+wahabu@users.noreply.github.com"

          git add -A
          git diff --cached --quiet && exit 0

          git commit -m "generated"

          git fetch origin
          git pull --rebase origin main || true
          git push origin HEAD:main
