name: GitHub-Profile-3D-Contrib

on:
  schedule:
    # Run the workflow daily at 18:00 UTC (03:00 JST)
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
      # Generate 3D contribution graph
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      # Setup Python 3.10
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # Run the script to change the border of the 3D contribution graph
      - run: python ./bin/change-border.py profile-3d-contrib/profile-night-rainbow.svg profile-3d-contrib/profile-night-rainbow-with-border.svg
      # Commit and push the changes
      - name: Commit & Push
        uses: EndBug/add-and-commit@v7.3.0
        with:
          author_name: wahabu
          author_email: ritscg2hibo@gmail.com
          message: 'generated'
          token: ${{ secrets.ACCESS_TOKEN }}
